# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Build uniapp
        run: |
          ls -alh
          sudo npm update
          cd uniapp_glaucoma/
          yarn install
          npm run build:app-plus
          ls -alh dist/build/app-plus
          cd ../
          ls -alh
      
      - name: Replace the Uniapp package in Android
        run: |
          rm -rf app/src/main/assets/apps/__UNI__E90A4C7/www
          mv uniapp_glaucoma/dist/build/app-plus app/src/main/assets/apps/__UNI__E90A4C7/www

      # Runs a set of commands using the runners shell
      - name: Build Android
        run: |
          echo test, and deploy your project.
          java --version
          gradle assembleRelease
          ls -alh app/build/outputs/apk/release
      
      - name: Upload APK to attachment
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk
